# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [2]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [3]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [4]:
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [5]:
total_per_consumer = pd.DataFrame(data.groupby(['CustomerID', 'ProductName'])['Quantity'].sum()).reset_index()
total_per_consumer.head()

   CustomerID                    ProductName  Quantity
0          33               Apricots - Dried         1
1          33              Assorted Desserts         1
2          33        Bandage - Flexible Neon         1
3          33  Bar Mix - Pina Colada, 355 Ml         1
4          33         Beans - Kidney, Canned         1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [6]:
pr_by_cst = pd.pivot_table(total_per_consumer, 
                           index='ProductName', 
                           columns='CustomerID', 
                           values='Quantity', 
                           fill_value=0)
pr_by_cst

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0,0,0,0,0,0,0,1,0,0,...,0,25,0,0,0,0,0,0,0,0
"Appetizer - Mini Egg Roll, Shrimp",0,0,0,0,0,0,0,0,0,0,...,25,25,0,0,0,0,0,0,0,0
Appetizer - Mushroom Tart,0,0,0,0,0,0,0,1,0,0,...,25,0,0,0,0,0,0,0,25,0
Appetizer - Sausage Rolls,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,25,25,25,0,25,0
Apricots - Dried,1,0,0,0,1,0,0,0,0,0,...,0,25,0,0,0,0,0,0,0,0
Apricots - Halves,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,25,50,25,0,25,25
Apricots Fresh,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,25
Arizona - Green Tea,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,25,0,0,0,0
Artichokes - Jerusalem,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Assorted Desserts,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,25,0,0,25
Bacardi Breezer - Tropical,0,1,1,0,0,0,3,0,1,0,...,25,0,0,0,0,25,0,0,0,0
Bagel - Plain,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,25,0,50,0
Baking Powder,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Banana - Leaves,0,0,1,0,1,1,0,0,0,0,...,0,25,0,0,0,0,0,0,0,25
Banana Turning,0,0,0,0,0,1,0,0,0,0,...,0,25,0,0,0,0,0,0,0,25
Bananas,0,0,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,25
Bandage - Fexible 1x3,0,0,0,0,0,0,0,0,0,0,...,25,0,0,0,0,0,0,0,0,0
Bandage - Flexible Neon,1,0,1,0,0,0,0,0,0,0,...,0,0,25,0,0,0,0,0,0,0
Bar - Granola Trail Mix Fruit Nut,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Bar Mix - Pina Colada, 355 Ml",1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,25,0,0,0,0,0
Barramundi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,25,0,0,0,25,25,0
Bay Leaf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,25,25,0,0,0
Beans - Kidney White,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,25,0
"Beans - Kidney, Canned",1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Beans - Kidney, Red Dry",0,0,0,0,0,0,0,0,1,0,...,25,0,0,0,0,25,0,0,0,0
Beans - Wax,0,0,0,0,1,0,0,0,0,0,...,25,0,0,0,0,0,25,0,25,0
"Beef - Chuck, Boneless",1,0,0,0,0,0,0,0,1,0,...,0,0,25,0,0,0,0,0,0,0
Beef - Ground Medium,0,1,0,1,0,0,0,0,1,0,...,25,0,0,0,0,0,0,50,25,0
"Beef - Ground, Extra Lean, Fresh",0,0,0,0,0,1,1,0,1,0,...,0,0,0,0,0,0,0,25,0,0
Beef - Inside Round,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,25,0,0,0,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wine - Fume Blanc Fetzer,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,25
Wine - Gato Negro Cabernet,1,1,1,0,0,0,0,0,0,0,...,25,0,0,25,25,0,0,0,0,0
Wine - Hardys Bankside Shiraz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,25
Wine - Magnotta - Belpaese,0,0,0,1,0,0,0,1,0,0,...,25,0,25,0,0,0,0,0,0,0
Wine - Magnotta - Cab Sauv,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,25,0,0,0,0
"Wine - Magnotta, Merlot Sr Vqa",0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,25,0
Wine - Pinot Noir Latour,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,25,0
Wine - Prosecco Valdobiaddene,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,25,0,0,0,0,0
"Wine - Red, Colio Cabernet",0,0,0,0,0,0,0,0,0,1,...,0,0,50,0,25,0,0,0,0,0
"Wine - Red, Cooking",0,0,0,1,0,0,0,0,0,0,...,25,0,0,0,25,0,0,0,0,0
"Wine - Red, Harrow Estates, Cab",0,0,0,0,0,0,0,0,0,0,...,0,0,0,25,25,0,0,0,0,0
Wine - Redchard Merritt,0,0,1,0,0,0,0,0,0,0,...,0,0,25,0,0,0,0,0,0,0
Wine - Ruffino Chianti,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,25,25,0,0,0
Wine - Sogrape Mateus Rose,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Wine - Toasted Head,0,0,0,0,0,0,0,2,0,0,...,0,0,25,0,25,0,0,0,0,0
Wine - Two Oceans Cabernet,1,0,0,1,1,0,1,1,0,0,...,0,0,0,25,0,0,0,0,0,0
Wine - Valpolicella Masi,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Wine - Vidal Icewine Magnotta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,25,0,0,0,25,0,0
Wine - Vineland Estate Semi - Dry,0,0,0,0,0,0,0,0,0,1,...,0,0,0,25,0,0,0,0,0,0
Wine - White Cab Sauv.on,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
"Wine - White, Colubia Cresh",0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,25,0,0,0,0,0
"Wine - White, Mosel Gold",0,0,0,0,1,0,1,0,0,0,...,0,25,0,0,0,25,0,50,0,0
"Wine - White, Schroder And Schyl",0,0,0,0,1,0,0,0,0,0,...,25,0,0,25,0,25,0,0,0,0
Wine - Wyndham Estate Bin 777,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,25,0
Wonton Wrappers,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Yeast Dry - Fermipan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,25,0,0,0,0,0,0
Yoghurt Tubes,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,25,0,0
"Yogurt - Blueberry, 175 Gr",0,1,0,0,0,0,0,0,0,0,...,25,0,0,25,0,0,0,0,0,0
Yogurt - French Vanilla,1,0,0,1,0,0,2,0,0,1,...,0,0,25,0,0,0,0,0,0,25
Zucchini - Yellow,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [7]:
cst_similarity = pd.DataFrame(1/(1 + squareform(pdist(pr_by_cst.T, 'euclidean'))), index=pr_by_cst.columns, columns=pr_by_cst.columns)
cst_similarity.tail()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
97928,0.004515,0.004521,0.004543,0.004526,0.004530,0.004533,0.004534,0.004526,0.004528,0.004523,...,0.003509,0.003509,0.003300,0.003653,0.003579,1.000000,0.003638,0.003418,0.003255,0.003245
98069,0.004583,0.004614,0.004595,0.004578,0.004578,0.004578,0.004589,0.004581,0.004585,0.004592,...,0.003509,0.003509,0.003369,0.003509,0.003496,0.003638,1.000000,0.003469,0.003345,0.003381
98159,0.004355,0.004367,0.004365,0.004365,0.004367,0.004363,0.004366,0.004363,0.004369,0.004365,...,0.003509,0.003565,0.003322,0.003431,0.003322,0.003418,0.003469,1.000000,0.003277,0.003266
98185,0.004167,0.004166,0.004179,0.004175,0.004177,0.004167,0.004168,0.004176,0.004172,0.004161,...,0.003311,0.003162,0.003255,0.003406,0.003172,0.003255,0.003345,0.003277,1.000000,0.003288
98200,0.004333,0.004335,0.004333,0.004339,0.004349,0.004347,0.004338,0.004335,0.004329,0.004347,...,0.003418,0.003345,0.003381,0.003444,0.003288,0.003245,0.003381,0.003266,0.003288,1.000000

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [8]:
#They are not really similar... is what I did correct?
users = pd.DataFrame(cst_similarity.loc[33].sort_values(ascending=False).head(6)).reset_index()
users

   CustomerID        33
0          33  1.000000
1         264  0.087047
2        3535  0.087047
3        3317  0.087047
4        2503  0.085983
5        3305  0.085638

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [9]:
similar = data[data['CustomerID'].isin(users['CustomerID'].unique())]
similar.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
159,264,Virgil,Small,24688,270,Cheese Cloth No 100,1
242,3535,Lana,Peters,2399506,270,Cheese Cloth No 100,1
527,33,Lindsay,Santana,1899667,432,Beer - Original Organic Lager,1
887,3305,Bernard,O'Neill,2025094,102,"Rosemary - Primerba, Paste",1
1017,33,Lindsay,Santana,6509275,417,"Lamb - Pieces, Diced",1

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [10]:
prod_ranking = pd.DataFrame(similar.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False)).reset_index()
prod_ranking.head()

                     ProductName  Quantity
0         Towels - Paper / Kraft         4
1          Pepper - Black, Whole         4
2          Veal - Inside, Choice         4
3  Wine - Ej Gallo Sierra Valley         3
4           Lettuce - Spring Mix         3

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [11]:
no_comprados = set(prod_ranking['ProductName'].unique()) - set(similar[similar['CustomerID'] == 33]['ProductName'].unique())

In [25]:
no_33 = prod_ranking[prod_ranking['ProductName'].isin(no_comprados)].sort_values(by='Quantity', ascending=False)
no_33.head()

                   ProductName  Quantity
3   Wine - Red, Colio Cabernet        86
7     Nut - Pistachio, Shelled        66
6      Creme De Banane - Marie        66
10     Napkin White - Starched        61
12                 Clam Nectar        57

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [15]:
customers = data['CustomerID'].unique()
recomendaciones = {}

for a in customers:
    users = pd.DataFrame(cst_similarity.loc[a].sort_values(ascending=False).head(6)).reset_index()
    similar = data[data['CustomerID'].isin(users['CustomerID'].unique())]
    prod_ranking = pd.DataFrame(similar.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False)).reset_index()
    no_comprados = set(prod_ranking['ProductName'].unique()) - set(similar[similar['CustomerID'] == a]['ProductName'].unique())
    recomendaciones[a] = list(prod_ranking[prod_ranking['ProductName'].isin(no_comprados)].sort_values(by='Quantity', ascending=False).head()['ProductName'])

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [18]:
rec_total = pd.DataFrame.from_dict(recomendaciones, orient='index')
rec_total = rec_total.reset_index()
rec_total.columns = ['CustomerID', 
                     'Recommendation 1', 
                     'Recommendation 2', 
                     'Recommendation 3', 
                     'Recommendation 4', 
                     'Recommendation 5']
rec_total.head()

,CustomerID,Recommendation 1,Recommendation 2,Recommendation 3,Recommendation 4,Recommendation 5
0,61288,Jagermeister,Chicken - Soup Base,Lime Cordial - Roses,Macaroons - Two Bite Choc,Dc Hikiage Hira Huba
1,77352,Tahini Paste,Wine - Valpolicella Masi,Tuna - Salad Premix,Chicken - Soup Base,Isomalt
2,40094,Bread - Italian Corn Meal Poly,Puree - Mocha,Grouper - Fresh,"Oregano - Dry, Rubbed",Sherry - Dry
3,23548,Squid - Tubes / Tenticles 10/20,Puree - Mocha,Bread - Raisin Walnut Oval,Banana Turning,Flavouring - Orange
4,78981,Vanilla Beans,Lettuce - Frisee,"Yogurt - Blueberry, 175 Gr",Beef - Inside Round,Pop Shoppe Cream Soda

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

In [19]:
similarity_correlation = pd.DataFrame(1/(1 + squareform(pdist(pr_by_cst.T, 'correlation'))), index=pr_by_cst.columns, columns=pr_by_cst.columns)
similarity_correlation.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.493776,0.529677,0.510360,0.506951,0.507217,0.487410,0.497932,0.499215,0.502499,...,0.493385,0.484376,0.493486,0.479867,0.499870,0.479764,0.493197,0.486457,0.491384,0.492072
200,0.493776,1.000000,0.499733,0.498575,0.482172,0.481921,0.519139,0.480599,0.499131,0.505459,...,0.504719,0.496170,0.517884,0.508954,0.492581,0.484514,0.534491,0.500253,0.484272,0.488735
264,0.529677,0.499733,1.000000,0.497579,0.513573,0.490305,0.503243,0.480936,0.502028,0.490242,...,0.508803,0.490805,0.499750,0.499162,0.517743,0.525278,0.511845,0.503500,0.515736,0.490875
356,0.510360,0.498575,0.497579,1.000000,0.490143,0.489778,0.501933,0.507803,0.482686,0.486354,...,0.499105,0.486660,0.498662,0.502228,0.494239,0.496086,0.484207,0.502204,0.506401,0.500631
412,0.506951,0.482172,0.513573,0.490143,1.000000,0.497577,0.505111,0.512470,0.493947,0.507777,...,0.488109,0.529502,0.492033,0.495264,0.504752,0.500064,0.481259,0.502418,0.505997,0.515015

In [22]:
customers = data['CustomerID'].unique()
recomenda_corr = {}

for a in customers:
    users = pd.DataFrame(similarity_correlation.loc[a].sort_values(ascending=False).head(6)).reset_index()
    similar = data[data['CustomerID'].isin(users['CustomerID'].unique())]
    prod_ranking = pd.DataFrame(similar.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False)).reset_index()
    no_comprados = set(prod_ranking['ProductName'].unique()) - set(similar[similar['CustomerID'] == a]['ProductName'].unique())
    recomenda_corr[a] = list(prod_ranking[prod_ranking['ProductName'].isin(no_comprados)].sort_values(by='Quantity', ascending=False).head()['ProductName'])

In [23]:
rec_corr = pd.DataFrame.from_dict(recomenda_corr, orient='index')
rec_corr = rec_corr.reset_index()
rec_corr.columns = ['CustomerID', 
                     'Recommendation 1', 
                     'Recommendation 2', 
                     'Recommendation 3', 
                     'Recommendation 4', 
                     'Recommendation 5']
rec_corr.head()

,CustomerID,Recommendation 1,Recommendation 2,Recommendation 3,Recommendation 4,Recommendation 5
0,61288,Wine - Two Oceans Cabernet,Jagermeister,Tofu - Firm,Appetizer - Sausage Rolls,Dc - Frozen Momji
1,77352,Fondant - Icing,Grenadine,Mangoes,Flour - Whole Wheat,Lettuce - Frisee
2,40094,Truffle Cups - Brown,"Bread - Roll, Soft White Round",Juice - V8 Splash,"Veal - Brisket, Provimi,bnls",Anchovy Paste - 56 G Tube
3,23548,Olives - Stuffed,Wine - Charddonnay Errazuriz,Soup - Campbells Tomato Ravioli,Assorted Desserts,Juice - Orange
4,78981,"Tart Shells - Sweet, 4",Sprouts - Baby Pea Tendrils,Artichokes - Jerusalem,"Appetizer - Mini Egg Roll, Shrimp",Chocolate - Dark